---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create docker container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: sleep infinity
      loop: "{{ molecule_yml.platforms }}"