---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu
    image: ubuntu:latest
    pre_build_image: true

provisioner:
  name: ansible
  connection_options:
    ansible_connection: docker

verifier:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy